# example netlify.toml
[build]
  command = "npm run build"
  functions = "src/functions"
  publish = "dist/ostaraV3"

[dev]
  command = "npm start"
  port = 4201
  publish = "src"
  functions = "src/functions"
  autoLaunch = false
