# example netlify.toml
[build]
  command = "npm run build"
  functions = "lambda"
  publish = "dist/ostaraV3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 4201
  publish = "src"
  functions = "lambda"
  autoLaunch = false
